language: python
python:
- '2.7'
dist: trusty
services:
- docker
- mysql
before_install:
- sudo apt-get -qq update
- sudo apt-get install graphviz
- pip install codecov
- pip install pytest-cov
- pip install codacy-coverage
- mysql -e 'CREATE DATABASE IF NOT EXISTS dqueue;'
install:
- pip install .
- pip install -r requirements.txt
- git clone http://git@github.com/volodymyrss/dqueue.git /tmp/dqueue && (cd /tmp/dqueue && pip install -r requirements.txt && pip install .)
script:
- py.test . --cov=./ -sv
- PYTHONPATH=./ py.test . --cov=./ -sv
after_success:
- coverage xml
- python-codacy-coverage -r coverage.xml
- codecov
env:
  global:
    - DDA_DEFAULT_CACHE_ROOT: /tmp/servercache  
    - DQUEUE_DATABASE_URL=mysql+pool://root:@localhost/dqueue?max_connections=42&stale_timeout=8001.2
    - secure: x5+c8IriljCAYTQJK+Dm50SqNLTCkI60B4/aoR7DynKxJsltS8dXMCK+AK1NSklr1jtiKfqAL3S3jqKKErXtTdOpObR7iCiVdv7sQC32kNcWO4rwo1tCH+nNtw73f2UPLjZ6BnETJ9pJsrULjbBRXod4bj6Xbv6AZ7wvjItzmA0z8LwAkK0diUxvj8bCMYkK4qwt2wRQ0J0V0n2G4FdsYEg40mBDvhMDFhvjb7Ad5bJhP/SwN9lYNIJaRByD4fqGncNq1Y8ua55mcqiffWKIqBSIRhkjS5iKm/3cHTarvWJmwWx1kvcBrzMqc9jn5tKaXjAjBiDTkRHqmSc/7hY5Asm4JSKnxQjQNa4T4vxlm6kpT+uhEmrz2cLke0FthmFqdHKahKfBXdmX+EYb9GVsyWvn/bRJjmTwVhPVixFl0LBJdYOd3sRKHIzAJEOhPVJw96MdRP+7InVIjV6reAzwkF1sR6Zxf8qK6ELWiVDBh7BqP4o3v5YgF4Ethte2fmXqk2mWeD/sN1zHNAYLzuUqnXTCCy6SxckQ79P/s7kpEOaz8+nLz98m1mpeeHYgWtXIWsmxW3SZy24A2UceXQQM481Q+NW4zFzvGleDfzSZ/idt64WUulfWjqKsp0d802oaZhXGbAbm/MMzStgAPk0o4wzXazfK9OIwxtkh/yzRcV0=
